use_frameworks!

target 'SQLiteObject_Example' do
  pod 'SQLiteObject', :path => '../'

  target 'SQLiteObject_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
